02 - TENSORFLOW TUTORIAL - BASIC MATRICES
============================================
By Ronny Restrepo

In [1]:
# ==============================================================================
#                                                                        IMPORTS
# ==============================================================================
from __future__ import print_function, division
import tensorflow as tf
import numpy as np

So we have played around with scalar values (0-dimensional tensors) now its 
time to start playing around with multi-dimensional tensors. 

## Constant Matrices
### TODO: move discussion about constants tot he next lesson. 

We saw earlier that  `tf.constant()` allows us to create a tensor with a 
particular value that we specify when we declare the graph. We used it 
previously to create scalar values. We can also use it to create matrices 
whose value we specify ahead of time using numpy. 

Below we create a matrix called `data`, and use this as the value for the 
tensor `a` in the graph. 

In [2]:
# ==============================================================================
#                                                                CREATE A MATRIX
# ==============================================================================
data = np.array([[1, 2, 3],
                 [2, 1, 2],
                 [3, 3, 3],
                 [4, 2, 4]])

# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    a = tf.constant(data, dtype=tf.float32)

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as sess:
    output_a = sess.run(a)
    print(output_a)

[[ 1.  2.  3.]
 [ 2.  1.  2.]
 [ 3.  3.  3.]
 [ 4.  2.  4.]]


## TODO: Add more ways of creating matrices in tensorflow
