05 - TENSORFLOW TUTORIAL - Placeholders
===========================================

In [1]:
# ==============================================================================
#                                                                        IMPORTS
# ==============================================================================
from __future__ import print_function, division
import tensorflow as tf
import numpy as np

Placeholders can be thought of as containers. They contain nothing on 
their own untill you fill them up. And just like containers, there are 
also restrictions about the shape and size of things you can put in it. 

Placeholders are useful when you have tensors whose values you want to 
control, and which you expect to be different on separate sessions. 
So for neural networks, you would want to use placeholders for the 
input vectors/matrices, since you will have a different of values for 
the training set, validation set, test set, and the inputs you use 
as your final product. 


## Declaring a placeholder 

Declaring a placeholder is just a matter of placing a line like 
the following when creating a graph. 

```python
tf.placeholder(tf.float32, shape=[3,4])
```

Here we declared that we want a tensor that is 3 by 4 in size 
and composed of elements that are or can be converted to 32 
bit floats. 

## Feed me! I'm hungry

A very important feature about placeholders is that they require 
feeding. We need to feed them some value everytime we start a new 
session. If we try to run through a graph, without feeding values 
to placeholders, then we get an error message such as:

    InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape dim { size: 3 } dim { size: 4 }

See for yourself, run the following code:

In [ ]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    a = tf.placeholder(tf.float32, shape=(3, 4))
    b = a * 2
    
# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    # run, but do not feed `a` explicitly
    output = session.run(b)
    print(output)

In order to feed **`a`** we can make use of the `feed_dict` argument 
in the `session.run()` method. The argument takes a dictionary, with 
the key being the placeholder objects you want to feed, and the 
values of the dictionary are the values you want to feed to the 
corresponding placceholder. 

If we now feed **`a`** a value, we get it to run properly wihtout errors. 

In [4]:
# Create an array to be fed to `a`
input_array = np.ones((3,4))

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    # run, but also feed `a` a value
    output = session.run(b, feed_dict={a: input_array})
    print(output)

[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
