# Multiplication and Dot Product

In [1]:
# ==============================================================================
#                                                                        IMPORTS
# ==============================================================================
from __future__ import print_function, division
import tensorflow as tf
import numpy as np

# Scalar times Tensor
**TODO: Add description text**

In [13]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 2x3 matrix
    a = tf.constant(np.array([[ 1, 2, 3],
                              [10,20,30]]),
                    dtype=tf.float32)

    # Scalar times Matrix
    c =  2 * a

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    output = session.run(c)
    print(output)

[[  2.   4.   6.]
 [ 20.  40.  60.]]


# Elementwise Multiplication

```python
a*b
``` 

Performs elementwise multiplication between two tensors of the same size

In [5]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 2x3 matrix
    a = tf.constant(np.array([[ 1, 2, 3],
                              [10,20,30]]),
                    dtype=tf.float32)
    # A 3x2 matrix
    b = tf.constant(np.array([[2, 2, 2],
                              [3, 3, 3]]),
                    dtype=tf.float32)

    # Elementwise multiplication
    c =  a * b

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    output = session.run(c)
    print(output)

[[  2.   4.   6.]
 [ 30.  60.  90.]]


# Dot Product
```
tf.matmul(a, b)
```

can be used to perform the deot product $a \cdot b$

In [12]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 2x3 matrix
    a = tf.constant(np.array([[1, 2, 3],
                              [2, 4, 6]]),
                            dtype=tf.float32)
    # A 3x2 matrix
    b = tf.constant(np.array([[1, 10],
                              [2, 20],
                              [3, 30]]),
                    dtype=tf.float32)

    # Dot Product them
    c = tf.matmul(a, b) #a * b

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    output = session.run(c)
    print(output)

[[  14.  140.]
 [  28.  280.]]
