# Tensor Sums / Addition

In [2]:
# ==============================================================================
#                                                                        IMPORTS
# ==============================================================================
from __future__ import print_function, division
import tensorflow as tf
import numpy as np

We can use:

```
tf.reduce_sum(a)
```

To get a sum of all the elements in a tensor. If we want to add along some specific axis we can specify that using: 

```
tf.reduce_sum(a, reduction_indices=[1])
```

In the example below we add up all the elements, sum along the rows, and along the columns. 


In [13]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 2x3 matrix
    a = tf.constant(np.array([[ 1, 2, 3],
                              [10,20,30]]),
                            dtype=tf.float32)

    # Sums of Elements
    x = tf.reduce_sum(a)                        # Sum of all elements
    y = tf.reduce_sum(a, reduction_indices=[1]) # Sum of each row
    z = tf.reduce_sum(a, reduction_indices=[0]) # Sum of each col

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    sum_all, sum_rows, sum_cols = session.run([x,y,z])
    print("Sum of all elements    : ", sum_all)
    print("Sum of each row    : ", sum_rows)
    print("Sum of each column : ", sum_cols)
    
    

Sum of all elements    :  66.0
Sum of each row    :  [  6.  60.]
Sum of each column :  [ 11.  22.  33.]


# Addition between tensors of same dimensions

**TODO: add some content here**


In [ ]:
# TODO: add code. 

# Adition of 2D tensor and a 1D tensor

Lets say that **`a`** is a 2D tensor, and **`b`** is a 
1D tensor, then in order for  **`a + b`** to work, then 
the dimensions have to match up as follows: 

$a = n \times m$

$b = m$

The *i'th* column of **`a`** is incremented by the *i'th* element of **`b`**. So it adds along columns. 


In [7]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 3x4 tensor
    a = tf.constant(np.array([[1,2,3,4],
                              [11,12,13,14],
                              [21,22,23,24]]), 
                            dtype=tf.float32)
    # A 1D tensor
    b = tf.constant([4,3,2,1], dtype=tf.float32)
    
    # Add them
    c = a + b

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    output = session.run(c)
    print(output)

[[  5.   5.   5.   5.]
 [ 15.  15.  15.  15.]
 [ 25.  25.  25.  25.]]


If we want to add along rows, then we have to make **`b`** a 
2D tensor, with dimensions $m \times 1$

In [9]:
# ------------------------------------------------
#                                    Build a graph
# ------------------------------------------------
graph = tf.Graph()
with graph.as_default():
    # A 3x4 tensor
    a = tf.constant(np.array([[1,2,3,4],
                              [11,12,13,14],
                              [21,22,23,24]]), 
                            dtype=tf.float32)
    # A 2D tensor, with only one column
    b = tf.constant(np.array([[3],
                              [2],
                              [1]]), dtype=tf.float32)
    
    # Add them
    c = a + b

# ------------------------------------------------
#              Create a session, and run the graph
# ------------------------------------------------
with tf.Session(graph=graph) as session:
    output = session.run(c)
    print(output)

[[  4.   5.   6.   7.]
 [ 13.  14.  15.  16.]
 [ 22.  23.  24.  25.]]
